# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request, workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install libscalapack-openmpi-dev libopenmpi-dev python3-dev python3-pip
    - name: Install dependencies
      run: |
        pip install mpi4py numpy scipy pytest Cython
    - name: Build
      run: python setup.py develop --user
    - name: Test
      run: mpirun -n 4 pytest -v
